---

- name: Enable kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ kernelModules }}"

- name: Setup sysctl params
  lineinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    insertafter: EOF
    line: "{{ item }}"
    create: yes
    loop: "{{ sysctlParams }}"

- name: Install CRI-O
  include_tasks: pkg.yml

- name: Start and enable CRI-O
  systemd:
    name: crio
    state: started
    enabled: true
